### ISSUE TITLE
Login screen becomes completely dark when entering in the fields

### ISSUE THREAD

**Issue by unixfox** [daehruoydeef/NextNotes#1]
On the login screen when I type something in the fields it becomes completely dark and I can't see what's in it anymore
![Screenshot_20190815-102922_NextNotes_1](https://user-images.githubusercontent.com/4016501/63082966-16e93700-bf37-11e9-8ad1-ab4eb356ffb4.png)

Same thing after logging in:
![Screenshot_20190815-103449_NextNotes_1](https://user-images.githubusercontent.com/4016501/63083199-aabb0300-bf37-11e9-9fca-a6bcc48dc4c0.png)

I'm using Android 9.

PS: Great app btw I love it!

**Comment by oskarsh** [comment]
Thanks for catching this! I will push a fix ASAP.

**Comment by oskarsh** [comment]
Do you use a system wide dark theme? I feel like this bug could be connected that Flutter wants to run the System Preferences but they will conflict with the rest of the Theming.

**Comment by unixfox** [comment]
Yes I do but it's not on during the daylight because it's set to `Automatic`.
![Screenshot_20190815-130322_LineageOS_Settings_1_1](https://user-images.githubusercontent.com/4016501/63091296-73575100-bf4d-11e9-9697-ad648c1d6b0f.png)
Moreover, if I disable it I still have the dark fields/the bug:
![Screenshot_20190815-130712_NextNotes_1_1](https://user-images.githubusercontent.com/4016501/63091259-591d7300-bf4d-11e9-8693-9946a1b5b397.png)

**Comment by oskarsh** [comment]
@unixfox I just pushed a new Version the Alpha 2, beside minor improvements I try to fix the invisible Text on some Buttons and the Textfields. Could you please try again and report back if this is working for you. On all my devices it is working fine and I cannot verify if this indeed fixed it.

**Comment by unixfox** [comment]
Yes it's indeed fixed!
![Screenshot_20190815-141113_NextNotes_1](https://user-images.githubusercontent.com/4016501/63093754-e2d13e80-bf55-11e9-93df-1054cfea6382.png)
Thanks for fixing the bug!
